### ISSUE TITLE
Can't install python Websocket-API

### ISSUE THREAD

**Issue by GunayAnach** [EXASOL/websocket-api#6]
When I try to install websocket API on python 3 I get the following error.

```
(C:\miniconda3) pip install git+http://github.com/EXASOL/websocket-api.git#egg=exasol-ws-api&subdirectory=python
Collecting exasol-ws-api from git+http://github.com/EXASOL/websocket-api.git#egg=exasol-ws-api
  Cloning http://github.com/EXASOL/websocket-api.git to c:\users\ganach\appdata\local\temp\pip-build-5hr2mu1i\exasol-ws-api
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\miniconda3\lib\tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\GAnach\\AppData\\Local\\Temp\\pip-build-5hr2mu1i\\exasol-ws-api\\setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\GAnach\AppData\Local\Temp\pip-build-5hr2mu1i\exasol-ws-api\
'subdirectory' is not recognized as an internal or external command,
operable program or batch file.
```

Any idea how I can get it installed?

Thank you very much.

**Comment by SSepi** [comment]
On Windows, try this:

pip install git+http://github.com/EXASOL/websocket-api.git#egg=exasol-ws-api^&subdirectory=python

Worked for me with Python 3 using the Anaconda Prompt.

**Comment by GunayAnach** [comment]
Thanks @SSepi worked great on both python 2 and python 3. Not sure what is the purpose of _egg=exasol-ws-api^_, although it worked without it.

Installation under Jupyter Notebook on AWS / Sagemaker was:
` !pip install git+http://github.com/EXASOL/websocket-api.git#subdirectory=python`
